Update pull request #3 from 4lm0nd/main
4lm0nd/SeleniumLv1 pull request #5
Opened 2022-11-16 20:19 UTC by 4lm0nd

Project Update

2022-11-18 12:41 UTC, nbmhoang commented on Utilities/railway/Utilities.java
> +    public String getDateLaterFromCurrentDate(int days) {
For any method that interact to Date/Time, my advice is use LocalDate(for date) and LocalDateTime(for date time). Its provide many method to do this

2022-11-18 12:41 UTC, nbmhoang commented on PageObjects/railway/GeneralPage.java
> +        element.sendKeys(Keys.PAGE_DOWN);
Why we use this key here?

2022-11-18 12:42 UTC, nbmhoang commented on Utilities/railway/Utilities.java
> +    public String getDateLaterFromCurrentDate(int days) {
Also, method come from this class should be declared as **static**

2022-11-21 09:36 UTC, 4lm0nd commented on Utilities/railway/Utilities.java
> +    public String getDateLaterFromCurrentDate(int days) {
update changes

2022-11-21 09:36 UTC, 4lm0nd commented on PageObjects/railway/GeneralPage.java
> +        element.sendKeys(Keys.PAGE_DOWN);
press page down button on the keyboard cho scroll page down

2022-11-21 09:38 UTC, nbmhoang commented on PageObjects/railway/GeneralPage.java
> +        element.sendKeys(Keys.PAGE_DOWN);
Could we use Javascript here?

2022-11-21 09:46 UTC, 4lm0nd commented on PageObjects/railway/GeneralPage.java
> +        element.sendKeys(Keys.PAGE_DOWN);
yes, but why we should use javascrip instead of key page down?

2022-11-21 09:47 UTC, nbmhoang commented on PageObjects/railway/GeneralPage.java
> +        element.sendKeys(Keys.PAGE_DOWN);
It will same as users behavior(users scroll by mouse, not press key)

2022-11-21 12:57 UTC, 4lm0nd commented on PageObjects/railway/GeneralPage.java
> +        element.sendKeys(Keys.PAGE_DOWN);
update changes :)))

2022-11-22 07:38 UTC, nbmhoang requested changes
Exception Constants/DriverManager class, all properties inside class/test case must not be **static**

2022-11-24 03:15 UTC, nbmhoang requested changes
Rename data object class name and use correct constructor/getter/setter

2022-11-24 06:52 UTC, 4lm0nd commented on DataObject/railway/BookTicket.java
> +    private String TicketAmount;
"Ticket amount" field is a combobox. I use select item by text

2022-11-24 09:32 UTC, merged